[tool.poetry]
name = "gpt-dev"
version = "0.1.0"
description = ""
authors = ["GlitchiPitch <nikitareutsky@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
torch = "^2.4.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
